services:

  todojs_server:
    container_name: todojs_server
    build:
      context: .
    volumes:
      - .:/todojs
      - ./src/config/nginx.conf:/etc/nginx/sites-available/default
    ports:
      - "881:80"
      - "882:22"
    depends_on:
      - todojs_mysql

  todojs_mysql:
    image: mysql
    container_name: todojs_mysql
    environment:
      MYSQL_DATABASE: 'todojs_mysql'
      MYSQL_USER: 'todojs_mysql'
      MYSQL_PASSWORD: 'todojs_mysql'
      MYSQL_ROOT_PASSWORD: 'todojs_mysql_root'
    ports:
      - '883:3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db: null